from .project_list import ProjectListWidget
from .project_progress import ProjectProgressWidget
from .project_document import ProjectDocumentWidget
from .project_achievement import ProjectAchievementWidget